services:

  mysql:
    image: mysql:8.4
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce_user
      MYSQL_PASSWORD: Ecommerce@123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/ecommerce.sql:/docker-entrypoint-initdb.d/ecommerce.sql

  backend:
    image: ecommerce-backend
    container_name: ecommerce-backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: ecommerce_user
      DB_PASSWORD: Ecommerce@123
      DB_NAME: ecommerce
      DB_PORT: 3306
      JWT_SECRET: my_super_secret_key_12345
    ports:
      - "5000:5000"

  frontend:
    image: ecommerce-frontend
    container_name: ecommerce-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data:
